version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: intellidoc_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: intellidoc

  redis:
    image: redis:7-alpine
    container_name: intellidoc_redis
    ports:
      - "6379:6379"

  chromadb:
    image: chromadb/chroma:latest
    container_name: intellidoc_chroma
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma

volumes:
  mongo_data:
  chroma_data: